const ENV_VARIABLES = [
  "NODE_ENV",
  "PORT",
  "SESSION_SECRET",
  "JWT_KEY",
  "JWT_REFRESH_KEY",
  "DATABASE_URL",
  "INSTAGRAPI_REST_USERNAME",
  "INSTAGRAPI_REST_PASSWORD",
  "PASSWORD",
  "ADMIN_KEY",
];
const NODE_ENV_OPTIONS = ["development", "production", "testing"];

export { ENV_VARIABLES, NODE_ENV_OPTIONS };
